
   
name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: recursive
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      - name: Install dev dependencies
        run: npm ci

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0
        with:
          version: nightly

      - name: Run tests
        run: forge test